#US79549 - Task 3 - Permitir a criação de mais de uma solicitação ao mesmo tempo
natamelo/synapse-zapcot pull request #12
Opened 2019-09-30 19:50 UTC by dalesEwerton

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#changelog)
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

2019-10-01 13:57 UTC, natamelo requested changes
Apenas um comentário

2019-10-01 13:57 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +            if substation_object is None:
Esse código de validar a subestação não poderia estar no check_solicitation_params?

2019-10-01 13:57 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +        raise SynapseError(400, "Invalid staggered for equipment type 'Reator'.", Codes.INVALID_PARAM)
Este nome "staggered" tá muito estranho? Quer dizer o que?

2019-10-01 13:57 UTC, natamelo commented on synapse/storage/voltage_control.py
> +                " solicitation.amount, "
Amount é o melhor mesmo? Por que não quantity?

2019-10-01 13:57 UTC, natamelo commented on zapcot-test/src/test/java/Test05FilterSolicitationByCompany.java
> +        ServiceUtil.createSingleSolicitation(onsAccessToken, "LIGAR", "REATOR", "MIR", "5", "500kV", true, "CTEEP");
Gambiarra bonita aqui, né!? kkkkk createSingleSolicitation

2019-10-01 15:30 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +            if substation_object is None:
Poderia, porém, tem um _tradeoff_ ai.

Essa notação @inlineCallbacks, que permite criar métodos assincronos, só pode ser usada dentro da classe, então pra por esse pedaço do códico em check_solicitation_params eu teria que fazer essa função pertencer a classe, e a gente já tinha definido que essas funções auxiliares ficam fora da classe, por isso fiz assim.

2019-10-01 15:31 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +        raise SynapseError(400, "Invalid staggered for equipment type 'Reator'.", Codes.INVALID_PARAM)
Agora me falhou a memória o termo, mas era aquele termo que vocês pediram pra trocar por encadeado, que eu pesquisei a tradução e era isso aí.

2019-10-01 15:41 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +                " solicitation.amount, "
Bom isso depende se uma coisa é contável ou não no inglês. Se a gente pensa em Capacitores, o certo seria Quantity, se falamos de Reatores seria Number, acho q pela forma do plural dessas palavras. Mas como a gente quer representar várias coisas com esse termo eu preferi amount. Posso mudar se tu quiser.

2019-10-01 15:43 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test05FilterSolicitationByCompany.java
> +        ServiceUtil.createSingleSolicitation(onsAccessToken, "LIGAR", "REATOR", "MIR", "5", "500kV", true, "CTEEP");
Se todos os testes foram planejados previamente com o objetivo de criar uma única solicitação eu modifiquei o método pra criar uma única solicitação, pq é gambiarra?

2019-10-01 16:24 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +            if substation_object is None:
Entendi. Então, você pode criar uma função check_substation como pertencente a classe. Embora que esse método é um util... no futuro próximo deve tá em algum lugar que possa ser reusado facilmente.

2019-10-01 16:29 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +        raise SynapseError(400, "Invalid staggered for equipment type 'Reator'.", Codes.INVALID_PARAM)
massa

2019-10-01 16:31 UTC, natamelo commented on synapse/storage/voltage_control.py
> +                " solicitation.amount, "
Entendi. Vamos seguir assim.

2019-10-01 17:00 UTC, natamelo commented on zapcot-test/src/test/java/Test05FilterSolicitationByCompany.java
> +        ServiceUtil.createSingleSolicitation(onsAccessToken, "LIGAR", "REATOR", "MIR", "5", "500kV", true, "CTEEP");
Eu acho que o ideal seria usar o mesmo método que usa pra criar várias solicitações. Mas assim ficou bom. Pensando bem, fica até menos verborrágico.

2019-10-02 13:14 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +            if substation_object is None:
Feito

2019-10-04 11:38 UTC, natamelo approved these changes

2019-10-04 11:38 UTC, merged