US79552 - Task2 - Evoluir serviço rest de criação de solicitação com Transformador
natamelo/synapse-zapcot pull request #14
Opened 2019-10-03 14:12 UTC by dalesEwerton

2019-10-04 12:06 UTC, natamelo requested changes
Apenas alguns comentários.

2019-10-04 12:06 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +            voltage = None
Acho que é melhor criar um método para criar a solicitação por tipo de forma independente;
Por exemplo, create_solicitation_for_reactor; Nesse você pode tratar as especificidades de reactor e depois chamar o create_solicitation do store;
Importante: todos os atributos que não fazem parte da solicitação devem ser nulos;

2019-10-04 12:06 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +        check_transform_params(solicitation)
Massa!

2019-10-04 12:06 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +            staggered = None
Na teoria não precisa desses ifs, já que são feitas checagens anteriores;

2019-10-04 12:06 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +    if int(solicitation["amount"]) < 0:
Da pra encapsular em um método cada checagem dessa, como dito anteriormente.

2019-10-04 12:06 UTC, natamelo commented on zapcot-test/src/test/java/Test10CreateCapacitorSolicitation.java
> +                    body("error", equalTo("Voltage value cannot be saved for 'CAPACITOR'."));
Tu achas que precisa verificar esse tipo de situação? Tinha pensando em: validar os campos pelo tipo e os demais setava pra null;

2019-10-04 12:06 UTC, natamelo commented on zapcot-test/src/test/java/Test10CreateCapacitorSolicitation.java
> +                    body("error", equalTo("Invalid amount value for equipment type 'CAPACITOR'."));
A primeira inconsistência que ele encontrar, já retorna, né? Nesse momento, é o ideal. Depois, o ideal é validar campo a campo.

2019-10-04 16:17 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +            staggered = None
Pra certos tipos de equipamentos, voltagem é opcional, assim como para os outros campos que estão nessa parte, então a checagem é feita para alguns, caso uma requisição não preencha esse campo por ser opcional ele iria passar na validação e quebrar na hora de pedir ao storage pra criar pq nao conhece a chave

2019-10-07 16:20 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +            voltage = None
Eu pensei inicialmente em algo assim, mas decidi por isso de funções separadas que validam as solicitações antes de criar pq preciso validar todas antes de iniciar a criação, pensando que a operação tem q ser atomica, eu não posso criar três e subir um erro da quarta, por exemplo.

2019-10-07 17:15 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +            staggered = None
Eu fiz como a gente combinou na daily de sexta, removi esses IFs e setei pra null os valores que não não necessários

2019-10-07 17:16 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +    if int(solicitation["amount"]) < 0:
Feito

2019-10-07 17:17 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test10CreateCapacitorSolicitation.java
> +                    body("error", equalTo("Voltage value cannot be saved for 'CAPACITOR'."));
Removi esses testes e essas verificações também do código também, como falei num dos comentários acima

2019-10-11 09:45 UTC, merged