US1.3 - Criar serviço REST para criar solicitação
natamelo/synapse-zapcot pull request #3
Opened 2019-09-11 12:57 UTC by dalesEwerton

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#changelog)
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

2019-09-12 14:27 UTC, natamelo requested changes
Apenas alguns comentários. Talvez seja necessário merjar com a us5 pra os testes. Acho que é melhor merjar a us5 primeiro.

2019-09-12 14:27 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +        self.event_creation_handler = hs.get_event_creation_handler()
Precisa desse handler mesmo?

2019-09-12 14:27 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +    def create_solicitation(self, action, equipment, substation, bar, value, userId):
- Fazer comentário breve sobre o objetivo do método.
- Colocar um TODO: sobre definir as regras de negócio no futuro.

2019-09-12 14:27 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +        status = "NOT_ANSWERED"
Utilizar constante do status já definida em outro arquivo.

2019-09-12 14:27 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +    def get_substations_codes(self):
- deixar get_substation_codes

2019-09-12 14:27 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +        subs_codes = []
- deixar apenas codes;

2019-09-12 14:27 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +        subs = yield self.store.get_substations()
- melhor colocar substations mesmo

2019-09-12 14:27 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +        self._event_serializer = hs.get_event_client_serializer()
- tá usando esse event_serializer?;

2019-09-12 14:27 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +        self._voltage_control_handler = hs.get_voltage_control_handler()
- por que tá protected? é o ideal, mas não vi em outros lugares do projeto;

2019-09-12 14:27 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +        userId = requester.user.to_string()
- precisa do to_string mesmo? já não é string?

2019-09-12 14:27 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise InvalidClientTokenError(401, "Permission denied.")
- "Permission denied." / mudar para: "User should to belong ONS.";

2019-09-12 14:27 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise SynapseError(400, "Action must be valid.")
- Pra seguir o padrão, poderia colocar Invalid action!;

2019-09-12 14:27 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise SynapseError(400, "Equipment type must be valid.")
- Invalid equipment type!

2019-09-12 14:27 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +        subs_codes = yield self._voltage_control_handler.get_substations_codes(self=self)
- pode deixar codes;

2019-09-12 14:27 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise SynapseError(400, "Substation code must be valid.")
- "Invalid substation!"

2019-09-12 14:27 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +class VoltageControlStatusServlet(RestServlet):
- Por que criou outro servlet?

2019-09-12 14:27 UTC, natamelo commented on synapse/storage/voltage_control.py
> +        except Exception as e:
- é necessário este try?

2019-09-12 14:27 UTC, natamelo commented on synapse/storage/voltage_control.py
> +            raise StoreError(500, "Problem creating solicitation.")
- Store Error já não loga?

2019-09-12 14:27 UTC, natamelo commented on synapse/storage/voltage_control.py
> +            subs = yield self._simple_select_list(
- trocar subs por substations;

2019-09-12 14:27 UTC, natamelo commented on synapse/storage/voltage_control.py
> +        except Exception as e:
- mesmo comentário anterior;

2019-09-12 14:27 UTC, natamelo commented on zapcot-test/.classpath
> +<?xml version="1.0" encoding="UTF-8"?>
- Deveria subir esse arquivo mesmo?

2019-09-12 14:27 UTC, natamelo commented on zapcot-test/.project
> +<?xml version="1.0" encoding="UTF-8"?>
- Deveria subir esse arquivo mesmo?

2019-09-12 14:27 UTC, natamelo commented on zapcot-test/.settings/org.eclipse.jdt.apt.core.prefs
> +eclipse.preferences.version=1
- Deveria subir esse arquivo mesmo?

2019-09-12 14:27 UTC, natamelo commented on zapcot-test/.settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
- Deveria subir esse arquivo mesmo?
- Adicionar no .gitignore esses arquivos;

2019-09-12 14:27 UTC, natamelo commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +        Map<String, Object> login = new HashMap<>();
- Ver como está implementado na branch us5;

2019-09-12 14:27 UTC, natamelo commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +        solicitation.put("action", "LIGAR");
- Colocar na classe DataUtil; Ver como está implementado para User;
- Ver na branch US5;

2019-09-12 14:27 UTC, natamelo commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +        Assert.assertThat(error, CoreMatchers.equalTo("Action must be valid."));
Não precisa fazer um assert em separado! Pode fazer usando body("error", equalTo(...));

2019-09-12 14:27 UTC, natamelo commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +    public void test02CreateInvalidSolicitations() {
- Melhor quebrar esse teste em: CreateSolicitationWithInvalidAction, CreateSolicitationWithInvalidSubstation, etc...

2019-09-12 17:34 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +        userId = requester.user.to_string()
Precisa, peguei essa linha de outros serviços, não entendi direito, mas é como se o ID fosse um tipo de dado

2019-09-12 17:43 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +class VoltageControlStatusServlet(RestServlet):
Foi o pedaço da outra task q te falei q mandei sem querer

2019-09-12 17:44 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +        except Exception as e:
Sim, e o pessoal do synapse também costuma usar. O banco pode estar eventualmente inconsistente por algum motivo, se essa operação falhar fora do try/except o servidor quebra

2019-09-12 17:45 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +            raise StoreError(500, "Problem creating solicitation.")
Sim, porém não loga o código da exception. Novamente, to fazendo como os caras fazem nos outros storages

2019-09-12 18:07 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +    def create_solicitation(self, action, equipment, substation, bar, value, userId):
Não entendi o motivo

2019-09-12 18:08 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +        self.event_creation_handler = hs.get_event_creation_handler()
Removi

2019-09-12 18:08 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +        status = "NOT_ANSWERED"
Feito

2019-09-12 18:13 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +    def get_substations_codes(self):
Feito

2019-09-12 18:14 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +        subs_codes = []
Feito

2019-09-12 18:15 UTC, dalesEwerton commented on synapse/handlers/voltage_control.py
> +        subs = yield self.store.get_substations()
Me perdi com tanta substation, era pra desfazer o outro pedido?

2019-09-12 18:15 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +        self._event_serializer = hs.get_event_client_serializer()
Removi

2019-09-12 18:16 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +        self._voltage_control_handler = hs.get_voltage_control_handler()
Eu acho que vi assim no serviço de notificações

2019-09-12 18:17 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise InvalidClientTokenError(401, "Permission denied.")
Mudei

2019-09-12 18:17 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise SynapseError(400, "Action must be valid.")
Feito

2019-09-12 18:17 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise SynapseError(400, "Equipment type must be valid.")
Feito

2019-09-12 18:17 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +        subs_codes = yield self._voltage_control_handler.get_substations_codes(self=self)
Feito

2019-09-12 18:17 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise SynapseError(400, "Substation code must be valid.")
Feito

2019-09-12 18:18 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +            subs = yield self._simple_select_list(
Feito

2019-09-12 18:18 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +        except Exception as e:
Mesma resposta anterior

2019-09-12 18:18 UTC, dalesEwerton commented on zapcot-test/.classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Feito

2019-09-12 18:18 UTC, dalesEwerton commented on zapcot-test/.project
> +<?xml version="1.0" encoding="UTF-8"?>
Feito

2019-09-12 18:18 UTC, dalesEwerton commented on zapcot-test/.settings/org.eclipse.jdt.apt.core.prefs
> +eclipse.preferences.version=1
Feito

2019-09-12 18:18 UTC, dalesEwerton commented on zapcot-test/.settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
Feito

2019-09-12 18:19 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +        Map<String, Object> login = new HashMap<>();
Aguardando o merge da US5

2019-09-12 18:19 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +        solicitation.put("action", "LIGAR");
Aguardando o merge da US5

2019-09-12 18:19 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +        Assert.assertThat(error, CoreMatchers.equalTo("Action must be valid."));
Aguardando o merge da US5

2019-09-12 18:19 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +    public void test02CreateInvalidSolicitations() {
Aguardando o merge da US5

2019-09-12 18:27 UTC, natamelo commented on synapse/handlers/voltage_control.py
> +    def create_solicitation(self, action, equipment, substation, bar, value, userId):
Sobre o ponto 1, a ideia é manter o padrão de comentários;
Sobre o ponto 2, a ideia é que a gente amarre as possibilidades quando um campo for obrigatório dependendo do valor de outro,... saca?

2019-09-12 18:41 UTC, natamelo requested changes
NO geral, observar arquivos do eclipse que não devem subir.

2019-09-12 18:41 UTC, natamelo commented on synapse/storage/voltage_control.py
> +        except Exception as e:
eu vi vários sem try... normalmente é usado quando se usa o txn também; mas blza; vou seguir esse padrão;

2019-09-12 18:41 UTC, natamelo commented on zapcot-test/.classpath
> +<?xml version="1.0" encoding="UTF-8"?>
por que? esse é um arquivo do eclipse, não?

2019-09-13 15:09 UTC, natamelo approved these changes
Ok

2019-09-13 15:09 UTC, natamelo commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +        payloadSolicitation.put("action", "DESLIGAR");
Melhor usa o método que retorna o payload, não?

2019-09-13 15:09 UTC, natamelo commented on zapcot-test/src/test/java/Test02CreateVoltageControlSolicitation.java
> +                    body("soft_logout", equalTo("User should to belong ONS."));
- o que é soft_logout?

2019-09-13 15:14 UTC, merged