US2 - Eu, como operador ONS, quero poder cancelar solicitações de controle que 1) ainda não foram tornadas ciente pelos operadores da CTEEP; 2) solicitadas há no máximo há 5 minutos.
natamelo/synapse-zapcot pull request #6
Opened 2019-09-16 18:51 UTC by dalesEwerton

**OBS** - Vai ser necessário, ao concluir a US6, voltar nos testes dessa US recuperando as solicitações criadas para poder tornar esse módulo de testes totalmente independente.

2019-09-17 18:49 UTC, natamelo requested changes
Muito bom. Só alguns comentários.

2019-09-17 18:49 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise SynapseError(404, "Solicitation was not found.", Codes.NOT_FOUND)
Pode deixar Solicitation not found

2019-09-17 18:49 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            return (200, {"message": "Solicitation status changed."})
Temos que padronizar esse retorno. Não tava colocando atributo para mensagem. Mas podemos seguir assim a partir da agora.

2019-09-17 18:49 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +    def _validate_creation_time(self, creation_ts):
Melhor is_valid_create_time... por que você espera um retorno. Outra opção é lançar exceção dentro do método. Mas o nome fica o mesmo.

2019-09-17 18:49 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +    def _validate_status_change(self, atual_status, new_status, company_code, creation_ts):
mudar company_code para user_company_code

2019-09-17 18:49 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            elif atual_status != SolicitationStatus.NOT_ANSWERED:
melhor current_status

2019-09-17 18:49 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +                raise InvalidClientTokenError(401, error_message)
Acho que o código de erro melhor não é esse. Melhor: UnauthorizedUserError

2019-09-17 18:49 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +                raise InvalidClientTokenError(401, error_message)
Memo comentário anterior

2019-09-17 18:49 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +                raise InvalidClientTokenError(401, error_message)
Vamos ter muitos erros repetidos em vários lugares. Depois podemos criar uma classe pra não precisar de ficar repetindo.

2019-09-17 18:49 UTC, natamelo commented on synapse/storage/voltage_control.py
> +                dict(id=id),
Normalmente, o pessoal usa { }, mas ok

2019-09-17 18:49 UTC, natamelo commented on synapse/storage/voltage_control.py
> +            if result:
precisa desse if mesmo?

2019-09-17 18:49 UTC, natamelo commented on synapse/storage/voltage_control.py
> +        except Exception as e:
fico agoniado com esse try aqui... mas ok

2019-09-17 18:49 UTC, natamelo commented on synapse/storage/voltage_control.py
> +            logger.warning("ged_solicitation failed: %s", e)
get*

2019-09-17 18:49 UTC, natamelo commented on synapse/storage/voltage_control.py
> +            updates = dict(status=new_status, update_timestamp=update_ts)
Tem alguma motivo de usar "dict"? Melhor deixar como o "padrão".

2019-09-17 18:49 UTC, natamelo commented on synapse/storage/voltage_control.py
> +                keyvalues= dict(id=id),
Mesmo comentário...

2019-09-17 18:49 UTC, natamelo commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +public class Test05ChangeControlSolicitationStatus {
Vai conflitar... mas mudo o meu pra Test06

2019-09-17 18:49 UTC, natamelo commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +        String access_token = RestAssured.
Como não faz parte do teste principal... usar um método auxiliar do ServiceUtil. Ver como eu usei na US4

2019-09-17 18:49 UTC, natamelo commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +        access_token = RestAssured.
Deixar a indentação como no caso anterior. 
give ().
    header().
    body()....

2019-09-17 18:49 UTC, natamelo commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +                body("message", equalTo("Solicitation status changed."));
O ideal seria recuperar a solicitação e verificar o seu status.

2019-09-17 18:49 UTC, natamelo commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +        String access_token = RestAssured.
Dá pra encapsular em um método. Mas pode deixar pra depois.

2019-09-17 18:49 UTC, natamelo commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +    public void test03InvalidStatusChange() {
Seria mais melhor InconsistentStatusChange... Invalid seria um status que não existe.

2019-09-18 12:48 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            raise SynapseError(404, "Solicitation was not found.", Codes.NOT_FOUND)
Feito

2019-09-18 12:48 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +    def _validate_creation_time(self, creation_ts):
Feito

2019-09-18 12:48 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +    def _validate_status_change(self, atual_status, new_status, company_code, creation_ts):
Feito

2019-09-18 12:48 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +            elif atual_status != SolicitationStatus.NOT_ANSWERED:
Feito

2019-09-18 12:48 UTC, dalesEwerton commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +                raise InvalidClientTokenError(401, error_message)
Não encontrei esse

2019-09-18 12:50 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +                dict(id=id),
Em alguns eles usam assim, mas mudei os meus pra {} mesmo

2019-09-18 12:51 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +            if result:
Eu acho q não, mas peguei de outro lugar que eles tavam usando o mesmo método, então não sei se existe um problema nesses métodos pra eles ficarem fazendo isso ou é só dupla precaução mesmo

2019-09-18 12:51 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +            logger.warning("ged_solicitation failed: %s", e)
Feito

2019-09-18 12:51 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +            updates = dict(status=new_status, update_timestamp=update_ts)
Feito

2019-09-18 12:51 UTC, dalesEwerton commented on synapse/storage/voltage_control.py
> +                keyvalues= dict(id=id),
Feito

2019-09-18 12:51 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +public class Test05ChangeControlSolicitationStatus {
Eu mudei pra 06

2019-09-18 12:53 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +        String access_token = RestAssured.
Feito

2019-09-18 12:53 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +        access_token = RestAssured.
Feito

2019-09-18 12:55 UTC, dalesEwerton commented on zapcot-test/src/test/java/Test05ChangeControlSolicitationStatus.java
> +    public void test03InvalidStatusChange() {
Feito

2019-09-18 13:17 UTC, natamelo approved these changes
Ok, muito bom!

2019-09-18 13:17 UTC, natamelo commented on synapse/rest/client/v2_alpha/voltage_control_solicitation.py
> +                raise InvalidClientTokenError(401, error_message)
Você pode criar hehehe

2019-09-18 13:17 UTC, merged